# Generated by Django 5.0.6 on 2024-07-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_chain_of_thoughts', models.TextField()),
                ('content_sql', models.TextField()),
                ('content_reply_to_user', models.TextField()),
                ('result_count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
