# Generated by Django 5.0.6 on 2024-07-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_messagemodel_delete_react'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(max_length=255)),
            ],
        ),
    ]
