# Generated by Django 5.0.6 on 2024-07-15 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_mainpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbconnect',
            name='db_type',
        ),
        migrations.AddField(
            model_name='dbconnect',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
